### ISSUE TITLE
circular rainbow effect

### ISSUE THREAD

**Issue by yumyyummy** [XanClic/leddy#2]
sorry if i open an issue but i'm a bit noob
is there any way that i can get a rainbow that moves in a circular position?
i mean is there any effect that can make the rainbow go up right then up left then down left and then down right?

**Comment by XanClic** [comment]
Hi,

Most of the effects provided are ones built into the keyboard (everything that `leddy --help` doesn’t sort under “software effects”). There is no such effect built into the keyboard, as far as I’m aware, so it wouldn’t be trivial to implement.
However, it is theoretically possible to implement your idea as a software effect, i.e. by leddy running in the background and continuously updating all keyboard LEDs to provide the desired effect (just as is done for the `screen-capture` and `sound-spectrum` effects). The obvious problem is that someone™ would need to implement it.

I can’t and definitely won’t promise that I’ll be that someone who implements it. But I’ll keep your idea in mind and update this issue in case I do get to it.

**Comment by yumyyummy** [comment]
Thanks for the reply, I could try to implement the function, I know a little the rust programming language but I could try, thank you again for the source code, if I make it I’ll let you know, have a nice day.
