### ISSUE TITLE
Currently there is no license

### ISSUE THREAD

**Issue by jmir1** [XanClic/leddy#5]
Hi there, thanks so much for this program!

I wanted to package it for NixOS (https://github.com/NixOS/nixpkgs/pull/348613).

What do you think about publishing this under a free license?

**Comment by XanClic** [comment]
Crap, you're right. I don't know how I forgot, it's supposed to be GPLv3. I'll fix it tomorrow.

**Comment by XanClic** [comment]
(Misclicked, that's what happens when I try to use a phone for writing Github comments)
